OrdererOrgs:
  - Name: Orderer
    Domain: foi.org
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Awesome Agency
    Domain: awesome.agency
    Specs:
      - Hostname: anchor
      - Hostname: peer
    Users:
      Count: 2

  - Name: Pharmatic AG
    Domain: pharmatic.com
    Specs:
      - Hostname: anchor
      - Hostname: peer
    Users:
      Count: 2

  - Name: Magik Inc.
    Domain: magik.dev
    Specs:
      - Hostname: anchor
    Users:
      Count: 1
