OrdererOrgs:
  - Name: Orderer
    Domain: foi.org
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Awesome Agency
    Domain: awesome.agency
    EnableNodeOUs: true
    Specs:
      - Hostname: anchor
      - Hostname: peer
    Users:
      Count: 1

  - Name: Pharmatic AG
    Domain: pharmatic.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer
    Users:
      Count: 1

  - Name: Magik Intl.
    Domain: magik.org
    EnableNodeOUs: true
    Specs:
      - Hostname: peer
    Users:
      Count: 1
