version: '2'

volumes:
  orderer.foi.org:
  anchor.awesome.agency:
  peer.awesome.agency:
  peer.pharmatic.com:
  peer.magik.com:

networks:
  basic:
services:
  ca.awesome.agency:
    image: hyperledger/fabric-ca:${IMAGE_TAG}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-awesome-agency
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.awesome.agency-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/AWESOME_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.awesome.agency-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/AWESOME_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/awesome.agency/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.awesome.agency
    networks:
      - basic

  ca.pharmatic.com:
    image: hyperledger/fabric-ca:${IMAGE_TAG}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-pharmatic
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.pharmatic.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/PHARMATIC_CA_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.pharmatic.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/PHARMATIC_CA_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/pharmatic.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.pharmatic.com
    networks:
      - basic

  orderer.foi.org:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.foi.org
    container_name: orderer.foi.org
    networks:
      - basic

  anchor.awesome.agency:
    container_name: anchor.awesome.agency
    extends:
      file:  base/docker-compose-base.yaml
      service: anchor.awesome.agency
    networks:
      - basic

  # peer.awesome.agency:
  #   container_name: peer.awesome.agency
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer.awesome.agency
  #   networks:
  #     - basic

  peer.pharmatic.com:
    container_name: peer.pharmatic.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer.pharmatic.com
    networks:
      - basic

  # peer.magik.com:
  #   container_name: peer.magik.com
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer.magik.com
  #   networks:
  #     - basic
