// Code generated by protoc-gen-go. DO NOT EDIT.
// source: application.proto

/*
Package schema is a generated protocol buffer package.

It is generated from these files:
	application.proto
	project.proto

It has these top-level messages:
	Application
	ApplicationId
	ApplicationList
	PublishApplication
	Project
	ProjectId
	ProjectList
	PublishProject
*/
package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Application_State int32

const (
	Application_APPLIED   Application_State = 0
	Application_ACCEPTED  Application_State = 1
	Application_REJECTED  Application_State = 2
	Application_COMPLETED Application_State = 3
)

var Application_State_name = map[int32]string{
	0: "APPLIED",
	1: "ACCEPTED",
	2: "REJECTED",
	3: "COMPLETED",
}
var Application_State_value = map[string]int32{
	"APPLIED":   0,
	"ACCEPTED":  1,
	"REJECTED":  2,
	"COMPLETED": 3,
}

func (x Application_State) String() string {
	return proto.EnumName(Application_State_name, int32(x))
}
func (Application_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

// Application state
type Application struct {
	// Identification of applier
	Contractor string `protobuf:"bytes,1,opt,name=contractor" json:"contractor,omitempty"`
	ProjectId  string `protobuf:"bytes,2,opt,name=projectId" json:"projectId,omitempty"`
	// Proposed Price in cents
	Price       int64                      `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	State       Application_State          `protobuf:"varint,4,opt,name=state,enum=io.github.tophatcroat.hlf_contrator.schema.Application_State" json:"state,omitempty"`
	Description string                     `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	ApplyDate   *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=apply_date,json=applyDate" json:"apply_date,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Application) GetContractor() string {
	if m != nil {
		return m.Contractor
	}
	return ""
}

func (m *Application) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Application) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Application) GetState() Application_State {
	if m != nil {
		return m.State
	}
	return Application_APPLIED
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Application) GetApplyDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.ApplyDate
	}
	return nil
}

type ApplicationId struct {
	Contractor string `protobuf:"bytes,1,opt,name=contractor" json:"contractor,omitempty"`
	ProjectId  string `protobuf:"bytes,2,opt,name=projectId" json:"projectId,omitempty"`
}

func (m *ApplicationId) Reset()                    { *m = ApplicationId{} }
func (m *ApplicationId) String() string            { return proto.CompactTextString(m) }
func (*ApplicationId) ProtoMessage()               {}
func (*ApplicationId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ApplicationId) GetContractor() string {
	if m != nil {
		return m.Contractor
	}
	return ""
}

func (m *ApplicationId) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type ApplicationList struct {
	Items []*Application `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ApplicationList) Reset()                    { *m = ApplicationList{} }
func (m *ApplicationList) String() string            { return proto.CompactTextString(m) }
func (*ApplicationList) ProtoMessage()               {}
func (*ApplicationList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApplicationList) GetItems() []*Application {
	if m != nil {
		return m.Items
	}
	return nil
}

type PublishApplication struct {
	ProjectName   string `protobuf:"bytes,1,opt,name=projectName" json:"projectName,omitempty"`
	ProjectIssuer string `protobuf:"bytes,2,opt,name=projectIssuer" json:"projectIssuer,omitempty"`
	// Proposed Price in cents
	Price       int64  `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
}

func (m *PublishApplication) Reset()                    { *m = PublishApplication{} }
func (m *PublishApplication) String() string            { return proto.CompactTextString(m) }
func (*PublishApplication) ProtoMessage()               {}
func (*PublishApplication) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PublishApplication) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

func (m *PublishApplication) GetProjectIssuer() string {
	if m != nil {
		return m.ProjectIssuer
	}
	return ""
}

func (m *PublishApplication) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *PublishApplication) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Application)(nil), "io.github.tophatcroat.hlf_contrator.schema.Application")
	proto.RegisterType((*ApplicationId)(nil), "io.github.tophatcroat.hlf_contrator.schema.ApplicationId")
	proto.RegisterType((*ApplicationList)(nil), "io.github.tophatcroat.hlf_contrator.schema.ApplicationList")
	proto.RegisterType((*PublishApplication)(nil), "io.github.tophatcroat.hlf_contrator.schema.PublishApplication")
	proto.RegisterEnum("io.github.tophatcroat.hlf_contrator.schema.Application_State", Application_State_name, Application_State_value)
}

func init() { proto.RegisterFile("application.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x49, 0x4b, 0xca, 0x76, 0x42, 0x61, 0xb1, 0x38, 0x44, 0x15, 0x82, 0x28, 0xe2, 0x10,
	0x21, 0xad, 0x23, 0x15, 0x09, 0xc4, 0x01, 0xa1, 0xd2, 0xe6, 0x50, 0xd4, 0x42, 0x94, 0xdd, 0x13,
	0x97, 0xc5, 0x75, 0xbc, 0x8d, 0x21, 0x59, 0x47, 0xf6, 0x94, 0x15, 0xef, 0xc1, 0xa3, 0xf1, 0x40,
	0x28, 0x71, 0xca, 0x86, 0x03, 0x02, 0xb1, 0xb7, 0xcc, 0x3f, 0xf1, 0x3f, 0x9f, 0x7f, 0x0f, 0x3c,
	0x60, 0x75, 0x5d, 0x4a, 0xce, 0x50, 0xaa, 0x4b, 0x5a, 0x6b, 0x85, 0x8a, 0x3c, 0x93, 0x8a, 0xee,
	0x24, 0x16, 0xfb, 0x2d, 0x45, 0x55, 0x17, 0x0c, 0xb9, 0x56, 0x0c, 0x69, 0x51, 0x5e, 0x9c, 0x73,
	0x75, 0x89, 0x9a, 0xa1, 0xd2, 0xd4, 0xf0, 0x42, 0x54, 0x6c, 0xfa, 0x64, 0xa7, 0xd4, 0xae, 0x14,
	0x71, 0x7b, 0x72, 0xbb, 0xbf, 0x88, 0x51, 0x56, 0xc2, 0x20, 0xab, 0x6a, 0x6b, 0x36, 0x7d, 0xd1,
	0x39, 0x71, 0x55, 0xc5, 0xd5, 0x95, 0xc4, 0x2f, 0xea, 0x2a, 0xde, 0xa9, 0x93, 0xb6, 0x79, 0xf2,
	0x95, 0x95, 0x32, 0x6f, 0xec, 0x4c, 0xfc, 0xeb, 0xd3, 0x9e, 0x0b, 0x7f, 0x0c, 0xc0, 0x9b, 0x5f,
	0xa3, 0x91, 0xc7, 0x00, 0x76, 0x38, 0x47, 0xa5, 0x7d, 0x27, 0x70, 0xa2, 0x71, 0xd6, 0x53, 0xc8,
	0x23, 0x18, 0xd7, 0x5a, 0x7d, 0x16, 0x1c, 0x57, 0xb9, 0x3f, 0x68, 0xdb, 0xd7, 0x02, 0x79, 0x08,
	0x6e, 0xad, 0x25, 0x17, 0xfe, 0x30, 0x70, 0xa2, 0x61, 0x66, 0x0b, 0x72, 0x0a, 0xae, 0x41, 0x86,
	0xc2, 0xbf, 0x1d, 0x38, 0xd1, 0xbd, 0xd9, 0x6b, 0xfa, 0xef, 0x17, 0xa7, 0x3d, 0x36, 0x7a, 0xda,
	0x98, 0x64, 0xd6, 0x8b, 0x04, 0xe0, 0xe5, 0xc2, 0x70, 0x2d, 0xeb, 0xa6, 0xe7, 0xbb, 0x2d, 0x4a,
	0x5f, 0x22, 0xaf, 0x00, 0x9a, 0xd0, 0xbf, 0x9d, 0xe7, 0xcd, 0xec, 0x51, 0xe0, 0x44, 0xde, 0x6c,
	0x4a, 0x6d, 0x90, 0xf4, 0x10, 0x24, 0x3d, 0x3b, 0x04, 0x99, 0x8d, 0xdb, 0xbf, 0x97, 0x0c, 0x45,
	0xf8, 0x06, 0xdc, 0x76, 0x18, 0xf1, 0xe0, 0xce, 0x3c, 0x4d, 0xd7, 0xab, 0x64, 0x79, 0x7c, 0x8b,
	0xdc, 0x85, 0xa3, 0xf9, 0x62, 0x91, 0xa4, 0x67, 0xc9, 0xf2, 0xd8, 0x69, 0xaa, 0x2c, 0x79, 0x97,
	0x2c, 0x9a, 0x6a, 0x40, 0x26, 0x30, 0x5e, 0x7c, 0xd8, 0xa4, 0xeb, 0xa4, 0x29, 0x87, 0xe1, 0x06,
	0x26, 0x3d, 0xf2, 0x55, 0x7e, 0xb3, 0x5c, 0xc3, 0x4f, 0x70, 0xbf, 0x67, 0xb7, 0x96, 0x06, 0xc9,
	0x06, 0x5c, 0x89, 0xa2, 0x32, 0xbe, 0x13, 0x0c, 0x23, 0x6f, 0xf6, 0xf2, 0x3f, 0x43, 0xcd, 0xac,
	0x4b, 0xf8, 0xdd, 0x01, 0x92, 0xee, 0xb7, 0xa5, 0x34, 0x45, 0x7f, 0x1d, 0x02, 0xf0, 0x3a, 0x8a,
	0xf7, 0xac, 0x12, 0x1d, 0x77, 0x5f, 0x22, 0x4f, 0x61, 0x72, 0xe0, 0x34, 0x66, 0x2f, 0x74, 0x07,
	0xff, 0xbb, 0xf8, 0x87, 0xc5, 0xf8, 0xeb, 0x1b, 0xbe, 0x3d, 0xfa, 0x38, 0xb2, 0xcc, 0xdb, 0x51,
	0xfb, 0x62, 0xcf, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x19, 0xf9, 0x34, 0xc0, 0x49, 0x03, 0x00,
	0x00,
}
