// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: state.proto

package schema

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *Application) Validate() error {
	if this.ApplyDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.ApplyDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("ApplyDate", err)
		}
	}
	return nil
}
func (this *Project) Validate() error {
	for _, item := range this.Applications {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Applications", err)
			}
		}
	}
	if this.OpenDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.OpenDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("OpenDate", err)
		}
	}
	if this.StartDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.StartDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("StartDate", err)
		}
	}
	if this.EndDate != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.EndDate); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("EndDate", err)
		}
	}
	return nil
}
func (this *ProjectId) Validate() error {
	return nil
}
func (this *ProjectList) Validate() error {
	for _, item := range this.Items {
		if item != nil {
			if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(item); err != nil {
				return github_com_mwitkow_go_proto_validators.FieldError("Items", err)
			}
		}
	}
	return nil
}
