// Code generated by protoc-gen-go. DO NOT EDIT.
// source: state.proto

package schema

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Application_State int32

const (
	Application_APPLIED   Application_State = 0
	Application_ACCEPTED  Application_State = 1
	Application_REJECTED  Application_State = 2
	Application_COMPLETED Application_State = 3
)

var Application_State_name = map[int32]string{
	0: "APPLIED",
	1: "ACCEPTED",
	2: "REJECTED",
	3: "COMPLETED",
}
var Application_State_value = map[string]int32{
	"APPLIED":   0,
	"ACCEPTED":  1,
	"REJECTED":  2,
	"COMPLETED": 3,
}

func (x Application_State) String() string {
	return proto.EnumName(Application_State_name, int32(x))
}
func (Application_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

type Project_State int32

const (
	Project_OPEN        Project_State = 0
	Project_IN_PROGRESS Project_State = 1
	Project_COMPLETED   Project_State = 2
	Project_CANCELED    Project_State = 3
)

var Project_State_name = map[int32]string{
	0: "OPEN",
	1: "IN_PROGRESS",
	2: "COMPLETED",
	3: "CANCELED",
}
var Project_State_value = map[string]int32{
	"OPEN":        0,
	"IN_PROGRESS": 1,
	"COMPLETED":   2,
	"CANCELED":    3,
}

func (x Project_State) String() string {
	return proto.EnumName(Project_State_name, int32(x))
}
func (Project_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1, 0} }

// Application state
type Application struct {
	// Identification of applier
	Contractor string `protobuf:"bytes,1,opt,name=contractor" json:"contractor,omitempty"`
	// Proposed Price in cents
	Price       int64                      `protobuf:"varint,2,opt,name=price" json:"price,omitempty"`
	State       Application_State          `protobuf:"varint,3,opt,name=state,enum=hr.foi.hlf_contrator.schema.Application_State" json:"state,omitempty"`
	Description string                     `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	ApplyDate   *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=apply_date,json=applyDate" json:"apply_date,omitempty"`
}

func (m *Application) Reset()                    { *m = Application{} }
func (m *Application) String() string            { return proto.CompactTextString(m) }
func (*Application) ProtoMessage()               {}
func (*Application) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Application) GetContractor() string {
	if m != nil {
		return m.Contractor
	}
	return ""
}

func (m *Application) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Application) GetState() Application_State {
	if m != nil {
		return m.State
	}
	return Application_APPLIED
}

func (m *Application) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Application) GetApplyDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.ApplyDate
	}
	return nil
}

// Project state
type Project struct {
	// Composite key is defined by Issuer and Name
	Issuer string `protobuf:"bytes,1,opt,name=issuer" json:"issuer,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// List of applicants for the project
	Applications []*Application `protobuf:"bytes,3,rep,name=applications" json:"applications,omitempty"`
	// Identification of the project Assessor, can be the same as Issuer
	Assessor  string                     `protobuf:"bytes,4,opt,name=assessor" json:"assessor,omitempty"`
	OpenDate  *google_protobuf.Timestamp `protobuf:"bytes,5,opt,name=open_date,json=openDate" json:"open_date,omitempty"`
	StartDate *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=start_date,json=startDate" json:"start_date,omitempty"`
	EndDate   *google_protobuf.Timestamp `protobuf:"bytes,7,opt,name=end_date,json=endDate" json:"end_date,omitempty"`
	// Estimated Project value in cents
	EstimatedValue uint64        `protobuf:"varint,8,opt,name=estimated_value,json=estimatedValue" json:"estimated_value,omitempty"`
	State          Project_State `protobuf:"varint,9,opt,name=state,enum=hr.foi.hlf_contrator.schema.Project_State" json:"state,omitempty"`
	Description    string        `protobuf:"bytes,10,opt,name=description" json:"description,omitempty"`
}

func (m *Project) Reset()                    { *m = Project{} }
func (m *Project) String() string            { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()               {}
func (*Project) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Project) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetApplications() []*Application {
	if m != nil {
		return m.Applications
	}
	return nil
}

func (m *Project) GetAssessor() string {
	if m != nil {
		return m.Assessor
	}
	return ""
}

func (m *Project) GetOpenDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.OpenDate
	}
	return nil
}

func (m *Project) GetStartDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.StartDate
	}
	return nil
}

func (m *Project) GetEndDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.EndDate
	}
	return nil
}

func (m *Project) GetEstimatedValue() uint64 {
	if m != nil {
		return m.EstimatedValue
	}
	return 0
}

func (m *Project) GetState() Project_State {
	if m != nil {
		return m.State
	}
	return Project_OPEN
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// ProjectId identifier part
type ProjetId struct {
	Issuer string `protobuf:"bytes,1,opt,name=issuer" json:"issuer,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *ProjetId) Reset()                    { *m = ProjetId{} }
func (m *ProjetId) String() string            { return proto.CompactTextString(m) }
func (*ProjetId) ProtoMessage()               {}
func (*ProjetId) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *ProjetId) GetIssuer() string {
	if m != nil {
		return m.Issuer
	}
	return ""
}

func (m *ProjetId) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// ProjectList list of projects
type ProjectList struct {
	Items []*Project `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
}

func (m *ProjectList) Reset()                    { *m = ProjectList{} }
func (m *ProjectList) String() string            { return proto.CompactTextString(m) }
func (*ProjectList) ProtoMessage()               {}
func (*ProjectList) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ProjectList) GetItems() []*Project {
	if m != nil {
		return m.Items
	}
	return nil
}

func init() {
	proto.RegisterType((*Application)(nil), "hr.foi.hlf_contrator.schema.Application")
	proto.RegisterType((*Project)(nil), "hr.foi.hlf_contrator.schema.Project")
	proto.RegisterType((*ProjetId)(nil), "hr.foi.hlf_contrator.schema.ProjetId")
	proto.RegisterType((*ProjectList)(nil), "hr.foi.hlf_contrator.schema.ProjectList")
	proto.RegisterEnum("hr.foi.hlf_contrator.schema.Application_State", Application_State_name, Application_State_value)
	proto.RegisterEnum("hr.foi.hlf_contrator.schema.Project_State", Project_State_name, Project_State_value)
}

func init() { proto.RegisterFile("state.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x8a, 0xd3, 0x40,
	0x14, 0xc6, 0x37, 0xfd, 0x9b, 0x9c, 0xac, 0xbb, 0x65, 0x10, 0x09, 0x15, 0x34, 0x14, 0xc1, 0xe0,
	0xc5, 0x2c, 0x54, 0x54, 0xf4, 0x46, 0x6b, 0x1a, 0xa4, 0x52, 0xdb, 0x30, 0x5d, 0xbc, 0xf0, 0xa6,
	0xcc, 0x26, 0xd3, 0x6d, 0x24, 0xc9, 0x84, 0xcc, 0x54, 0xf0, 0x4d, 0x7c, 0x03, 0x5f, 0x53, 0x66,
	0xa6, 0xdd, 0xed, 0x22, 0x74, 0xbb, 0x77, 0xfd, 0xce, 0x9c, 0xaf, 0xe7, 0x9c, 0x2f, 0x3f, 0x70,
	0x85, 0xa4, 0x92, 0xe1, 0xaa, 0xe6, 0x92, 0xa3, 0xa7, 0xeb, 0x1a, 0xaf, 0x78, 0x86, 0xd7, 0xf9,
	0x6a, 0x99, 0xf0, 0x52, 0xd6, 0x54, 0xf2, 0x1a, 0x8b, 0x64, 0xcd, 0x0a, 0xda, 0x7f, 0x7e, 0xcd,
	0xf9, 0x75, 0xce, 0x2e, 0x74, 0xeb, 0xd5, 0x66, 0x75, 0x21, 0xb3, 0x82, 0x09, 0x49, 0x8b, 0xca,
	0xb8, 0x07, 0x7f, 0x1b, 0xe0, 0x8e, 0xaa, 0x2a, 0xcf, 0x12, 0x2a, 0x33, 0x5e, 0xa2, 0x67, 0x00,
	0xe6, 0x4f, 0x12, 0xc9, 0x6b, 0xcf, 0xf2, 0xad, 0xc0, 0x21, 0x7b, 0x15, 0xf4, 0x18, 0xda, 0x55,
	0x9d, 0x25, 0xcc, 0x6b, 0xf8, 0x56, 0xd0, 0x24, 0x46, 0xa0, 0x31, 0xb4, 0xf5, 0x4a, 0x5e, 0xd3,
	0xb7, 0x82, 0xb3, 0x21, 0xc6, 0x07, 0x76, 0xc2, 0x7b, 0xe3, 0xf0, 0x42, 0xb9, 0x88, 0x31, 0x23,
	0x1f, 0xdc, 0x94, 0x89, 0xa4, 0xce, 0x2a, 0xf5, 0xe6, 0xb5, 0xf4, 0xf0, 0xfd, 0x12, 0x7a, 0x0f,
	0x40, 0xab, 0x2a, 0xff, 0xbd, 0x4c, 0xd5, 0xb0, 0xb6, 0x6f, 0x05, 0xee, 0xb0, 0x8f, 0xcd, 0x8d,
	0x78, 0x77, 0x23, 0xbe, 0xdc, 0xdd, 0x48, 0x1c, 0xdd, 0x3d, 0xa6, 0x92, 0x0d, 0x3e, 0x42, 0x5b,
	0x0f, 0x43, 0x2e, 0x74, 0x47, 0x71, 0x3c, 0x9d, 0x44, 0xe3, 0xde, 0x09, 0x3a, 0x05, 0x7b, 0x14,
	0x86, 0x51, 0x7c, 0x19, 0x8d, 0x7b, 0x96, 0x52, 0x24, 0xfa, 0x1a, 0x85, 0x4a, 0x35, 0xd0, 0x23,
	0x70, 0xc2, 0xf9, 0xb7, 0x78, 0x1a, 0x29, 0xd9, 0x1c, 0xfc, 0x69, 0x41, 0x37, 0xae, 0xf9, 0x4f,
	0x96, 0x48, 0xf4, 0x04, 0x3a, 0x99, 0x10, 0x1b, 0xb6, 0x4b, 0x68, 0xab, 0x10, 0x82, 0x56, 0x49,
	0x0b, 0x13, 0x8e, 0x43, 0xf4, 0x6f, 0x34, 0x85, 0x53, 0x7a, 0x7b, 0xb1, 0xf0, 0x9a, 0x7e, 0x33,
	0x70, 0x87, 0xc1, 0xb1, 0x11, 0x91, 0x3b, 0x6e, 0xd4, 0x07, 0x9b, 0x0a, 0xc1, 0x84, 0xe0, 0xf5,
	0x36, 0xa0, 0x1b, 0x8d, 0xde, 0x81, 0xc3, 0x2b, 0x56, 0x1e, 0x1b, 0x8e, 0xad, 0x9a, 0x55, 0x36,
	0x2a, 0x56, 0x21, 0x69, 0x2d, 0x8d, 0xb3, 0x73, 0x7f, 0xac, 0xba, 0x5b, 0x5b, 0xdf, 0x80, 0xcd,
	0xca, 0xd4, 0x18, 0xbb, 0xf7, 0x1a, 0xbb, 0xac, 0x4c, 0xb5, 0xed, 0x25, 0x9c, 0x33, 0x21, 0xb3,
	0x82, 0x4a, 0x96, 0x2e, 0x7f, 0xd1, 0x7c, 0xc3, 0x3c, 0xdb, 0xb7, 0x82, 0x16, 0x39, 0xbb, 0x29,
	0x7f, 0x57, 0x55, 0xf4, 0x69, 0x47, 0x96, 0xa3, 0xc9, 0x7a, 0x75, 0x30, 0xb6, 0xed, 0xe7, 0x39,
	0x48, 0x15, 0xfc, 0x47, 0xd5, 0x2d, 0x1a, 0x36, 0xb4, 0xe6, 0x71, 0x34, 0xeb, 0x9d, 0xa0, 0x73,
	0x70, 0x27, 0xb3, 0x65, 0x4c, 0xe6, 0x5f, 0x48, 0xb4, 0x58, 0xf4, 0xac, 0xbb, 0x30, 0x34, 0x14,
	0x29, 0xe1, 0x68, 0x16, 0x46, 0x53, 0x8d, 0xc6, 0x5b, 0xb0, 0xf5, 0x68, 0x39, 0x49, 0x1f, 0x82,
	0xc6, 0x60, 0x02, 0xee, 0x76, 0xe5, 0x69, 0x26, 0x24, 0xfa, 0x00, 0xed, 0x4c, 0xb2, 0x42, 0x78,
	0x96, 0x46, 0xe4, 0xc5, 0x31, 0xb7, 0x12, 0x63, 0xf9, 0x6c, 0xff, 0xe8, 0x98, 0x87, 0xab, 0x8e,
	0xce, 0xfd, 0xf5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x70, 0x6b, 0x29, 0x47, 0x25, 0x04, 0x00,
	0x00,
}
